### PR TITLE
Issue 4

### PR DESCRIPTION
**Pull request by Khyzad**
Chained if-statements together in DefaultSettings.equals()

---

This change is [Reviewable](https://reviewable.io/reviews/hawaiistatedigitalarchives/pid-webservice/22)

### CODE REVIEW

**Comment by dagnir** [comment]
Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

_[Minter/src/main/java/com/hida/model/DefaultSetting.java, line 81 [r1]](https://reviewable.io:443/reviews/hawaiistatedigitalarchives/pid-webservice/22#-KLyV7vizyctLcPOxFZq:-KLyV7vizyctLcPOxFZr:1490620556) ([raw file](https://github.com/hawaiistatedigitalarchives/pid-webservice/blob/56c92a5f052db860a93df8acbb507b7d03a3af18/Minter/src/main/java/com/hida/model/DefaultSetting.java#L81)):_

> ``` Java
>         final DefaultSetting other = (DefaultSetting) obj;
> 
>         return !(!Objects.equals(this.getPrepend(), other.getPrepend())
> ```

Instead of the double negation we can just return result of the equality test

``` java
return Objects.equals(this.getPrepend(), other.getPrepend())
    && Objects.equals(this.getPrefix(), other.getPrefix())
    && ...
```

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/hawaiistatedigitalarchives/pid-webservice/22)_

**Comment by Khyzad** [comment]
_[Minter/src/main/java/com/hida/model/DefaultSetting.java, line 81 [r1]](https://reviewable.io:443/reviews/hawaiistatedigitalarchives/pid-webservice/22#-KLyV7vizyctLcPOxFZq:-KLzu89yjGdKr2e3CtyF:498750507) ([raw file](https://github.com/hawaiistatedigitalarchives/pid-webservice/blob/56c92a5f052db860a93df8acbb507b7d03a3af18/Minter/src/main/java/com/hida/model/DefaultSetting.java#L81)):_
<details><summary>

<i>Previously, dagnir (Dongie Agnir) wrote…</i></summary>



> Instead of the double negation we can just return result of the equality test
> 
> ``` java
> return Objects.equals(this.getPrepend(), other.getPrepend())
>     && Objects.equals(this.getPrefix(), other.getPrefix())
>     && ...
> ```
> 
> </details>
> Wow, I can't believe I made a mistake like that.

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/hawaiistatedigitalarchives/pid-webservice/22)_

**Comment by dagnir** [comment]
Reviewed 1 of 1 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved.

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/hawaiistatedigitalarchives/pid-webservice/22)_

**Comment by dagnir** [comment]
Fixes #4

**Pull request merged**
